<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-C37CO4J" failures="2" tests="6" name="Test" time="0.332" errors="0" timestamp="2023-01-02T23:22:16 IST">
  <testcase classname="TestNGPrograms.day12RetryTest" name="Second" time="0.078">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at TestNGPrograms.day12RetryTest.Second(day12RetryTest.java:13)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- Second -->
  <testcase classname="TestNGPrograms.day12RetryTest" name="Third" time="0.006"/>
  <testcase classname="TestNGPrograms.day12RetryTest" name="first" time="0.005">
    <skipped/>
  </testcase> <!-- first -->
  <testcase classname="TestNGPrograms.day12RetryTest" name="first" time="0.006">
    <skipped/>
  </testcase> <!-- first -->
  <testcase classname="TestNGPrograms.day12RetryTest" name="first" time="0.007">
    <skipped/>
  </testcase> <!-- first -->
  <testcase classname="TestNGPrograms.day12RetryTest" name="first" time="0.007">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at TestNGPrograms.day12RetryTest.first(day12RetryTest.java:9)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- first -->
</testsuite> <!-- Test -->
